{"uuid":"eb2963bc-fdef-4492-b6b4-c69327318f66","historyId":"a1c4d7b4f25cae643f890c6bbc686fb8","fullName":"Pays.posfinaltesting.TakeOutTest.TakeOut_Cash_FullRefund_SelectRefund","labels":[{"name":"package","value":"Pays.posfinaltesting.TakeOutTest"},{"name":"testClass","value":"Pays.posfinaltesting.TakeOutTest"},{"name":"testMethod","value":"TakeOut_Cash_FullRefund_SelectRefund"},{"name":"parentSuite","value":"Suite"},{"name":"suite","value":"TakeOut_Cash_Refund"},{"name":"subSuite","value":"Pays.posfinaltesting.TakeOutTest"},{"name":"host","value":"Pratik"},{"name":"thread","value":"28524@Pratik.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"Takeout Cash Full Refund Selection"},{"name":"severity","value":"critical"}],"links":[{"name":"TC-023","type":"tms"}],"name":"TakeOut_Cash_FullRefund_SelectRefund","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Cash Refund failed expected [true] but found [false]","trace":"java.lang.AssertionError: Cash Refund failed expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat Pays.posfinaltesting.TakeOutTest.TakeOut_Cash_FullRefund_SelectRefund(TakeOutTest.java:326)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\n"},"stage":"finished","description":"Select Cash Full Refund for Takeout Order","steps":[],"attachments":[{"name":"Screenshot on Failure","source":"e336ab3a-3ac4-4a35-acc0-4a3d9a5f3b21-attachment"}],"parameters":[],"start":1742473305753,"stop":1742473316819}